apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  lablels:
    name: result-pod
    app: demo-voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports: 
      - containerPort: 6379
