apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
spec:
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-app 
    spec:
      containers:
        - name: result-app
          image: nithinnoronha/result-app:1 
  replicas: 3
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-app 
